### ISSUE TITLE
Mechanism for MARBL_generate_settings_file.py to change tracer module variables

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#455]
In the MOM interface, I'm working on defining CESM compsets that control `base_bio_on` and `abio_dic_on`. Currently the only way CESM users can change those values in `marbl_in` is by adding them to `user_nl_marbl`, but I'd like the `buildnml` script to be able to set them correctly based on the compset (well, based on an `env_run.xml` variable set differently by different compsets).

We already have a `GRID` option that gets passed to the default settings files:

```yaml
   lo2_consumption_scalef :
      dependencies : base_bio_on
      longname : Apply o2_consumption_scalef to o2 consumption (and request it as a forcing)
      subcategory : 3. config flags
      units : unitless
      datatype : logical
      default_value : # default value is resolution dependent!
         default : .false.
         GRID == "CESM_x1" : .true.
```

So maybe the tracer module section could add `BASE_BIO_ON` and `ABIO_DIC_ON` variables to that interface as well:

```yaml
tracer_modules :
   base_bio_on :
      longname : Control whether the base ecosystem tracer module is active
      subcategory : 1. tracer modules
      units : unitless
      datatype : logical
      default_value : # can be set by GCM
        default: .true.
        BASE_BIO_ON == "FALSE": .false.
      _append_to_config_keywords : true
   abio_dic_on :
      longname : Control whether abiotic carbon tracer module is active
      subcategory : 1. tracer modules
      units : unitless
      datatype : logical
      default_value :# can be set by GCM
        default: .false.
        ABIO_DIC_ON == "TRUE": .true.
      _append_to_config_keywords : true
```
